name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.18, 1.19, 1.20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          mkdir -p build/${{ matrix.os }}
          GOOS=${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }} GOARCH=amd64 go build -o build/${{ matrix.os }}/s7comm

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: s7comm-${{ matrix.os }}
          path: build/${{ matrix.os }}/s7comm${{ matrix.os == 'windows-latest' && '.exe' || '' }}
